version: '2'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    image: concora-emulator
    command: ls
    links:
      - postgres
    environment:
      CI: "true"
      RAILS_ENV: test
      DB_USER: postgres
      DB_HOST: postgres
      DB_TEST_USER: postgres
      DB_TEST_HOST: postgres
      DB_TEST_NAME: concora_emulator_test
      TESTDB_DATABASE_URL: "postgres://postgres:postgres@postgres/concora_emulator_test"